engines:
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true

ratings:
  paths:
    - src/**
    - test/**
exclude_paths:
  - dist/**/*
  - docs/**/*
  - examples/**/*
  - lib/**/*
  - node_modules/**/*
  - testem.js
